//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planet.Domain.Resources.OperationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Planet.Domain.Resources.OperationResources.OperationMessages", typeof(OperationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol listesi başarılı bir şekilde eklendi..
        /// </summary>
        public static string AddedCheckListToCardSuccessfully {
            get {
                return ResourceManager.GetString("AddedCheckListToCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart yorumu başarılı bir şekilde eklendi..
        /// </summary>
        public static string AddedCommentToCardSuccessfully {
            get {
                return ResourceManager.GetString("AddedCommentToCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} etiketi başarılı bir şekilde oluşturuldu..
        /// </summary>
        public static string AddedLabelSuccessfully {
            get {
                return ResourceManager.GetString("AddedLabelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} etiketi karta başarılı bir şekilde eklendi..
        /// </summary>
        public static string AddedLabelToCardSuccessfully {
            get {
                return ResourceManager.GetString("AddedLabelToCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} listesi başarılı bir şekilde oluşturuldu..
        /// </summary>
        public static string AddedListSuccessfully {
            get {
                return ResourceManager.GetString("AddedListSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano davet bağlantısı oluşturuldu. Bağlantıyı paylaşarak panonuza üyeleri davet edebilirsiniz..
        /// </summary>
        public static string BoardInvitationUrlCreatedSuccessfully {
            get {
                return ResourceManager.GetString("BoardInvitationUrlCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atanmak istenen etiket bulunamadı!.
        /// </summary>
        public static string BoardLabelNotFound {
            get {
                return ResourceManager.GetString("BoardLabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano listesi bulunamadı..
        /// </summary>
        public static string BoardListNotFound {
            get {
                return ResourceManager.GetString("BoardListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano bulunamadı..
        /// </summary>
        public static string BoardNotFound {
            get {
                return ResourceManager.GetString("BoardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi bir karta sahip bir pano listesi silinemez..
        /// </summary>
        public static string CanNotRemoveBoardListThatContainsCard {
            get {
                return ResourceManager.GetString("CanNotRemoveBoardListThatContainsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano sahibi üyelikten çıkarılamaz..
        /// </summary>
        public static string CanNotRemoveBoardOwner {
            get {
                return ResourceManager.GetString("CanNotRemoveBoardOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart bulunamadı!.
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol listesi bulunamadı. .
        /// </summary>
        public static string CheckListNotFound {
            get {
                return ResourceManager.GetString("CheckListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} panosu başarılı bir şekilde oluşturuldu..
        /// </summary>
        public static string CreatedBoardSuccessfully {
            get {
                return ResourceManager.GetString("CreatedBoardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart başarılı bir şekilde oluşturuldu..
        /// </summary>
        public static string CreatedCardSuccessfully {
            get {
                return ResourceManager.GetString("CreatedCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano kartlarına kontrol listesi eklemek için yetkiniz bulunmamaktadır. .
        /// </summary>
        public static string DoNotHavePermissionForAddCardCheckList {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForAddCardCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano kartlarına kullanıcı atamak için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForAssigningUserToCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForAssigningUserToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} panosu için üye davet yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForBoardInviting {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForBoardInviting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano için kart oluşturma yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForCreatingCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForCreatingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol listesi başlığını düzenlemek için yetkiniz bulunmamaktadır. .
        /// </summary>
        public static string DoNotHavePermissionForEditCardCheckListTitle {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditCardCheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano kartlarının yorumlarını düzenlemek için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForEditCardComment {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditCardComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano kartlarının açıklamasını düzenlemek için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForEditCardDescription {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano için bu kartın tarihini düzenleme yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForEditDateCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditDateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano özelliklerini değiştirmek için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForEditingBoard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartı düzenleme yetkiniz bulunmamaktadır!.
        /// </summary>
        public static string DoNotHavePermissionForEditingCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForEditingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano listelerini düzenlemek için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForManagingBoardLists {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForManagingBoardLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano üyelerini yönetmek için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForManagingBoardMembers {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForManagingBoardMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart taşıma işlemi için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForMovingCard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForMovingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart kontrol listesini kaldırmak için yetkiniz bulunmamaktadır. .
        /// </summary>
        public static string DoNotHavePermissionForRemoveCardCheckList {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForRemoveCardCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoyu görüntülemek için yetkiniz bulunmamaktadır..
        /// </summary>
        public static string DoNotHavePermissionForViewingBoard {
            get {
                return ResourceManager.GetString("DoNotHavePermissionForViewingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano özellikleri başarılı bir şekilde değiştirildi..
        /// </summary>
        public static string EditedBoardSuccessfully {
            get {
                return ResourceManager.GetString("EditedBoardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart günleri başarılı bir şekilde güncellendi..
        /// </summary>
        public static string EditedCardDateSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardDateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart açıklaması başarılı bir şekilde değiştirildi..
        /// </summary>
        public static string EditedCardDescriptionSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardDescriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart başlığı başarılı bir şekilde değiştirildi..
        /// </summary>
        public static string EditedCardTitleSuccessfully {
            get {
                return ResourceManager.GetString("EditedCardTitleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol listesi başlığı başarılı bir şekilde değiştirildi. .
        /// </summary>
        public static string EditedCheckListTitleSuccessfully {
            get {
                return ResourceManager.GetString("EditedCheckListTitleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen e-posta adresi daha önce kullanılmış..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen e-posta adresine kayıtlı bir kullanıcı bulunamadı..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davet bağlantısı artık geçerli değil..
        /// </summary>
        public static string ExpiredInvitationKey {
            get {
                return ResourceManager.GetString("ExpiredInvitationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} panosuna başarılı bir şekilde katıldınız..
        /// </summary>
        public static string JoinedBoardSuccessfully {
            get {
                return ResourceManager.GetString("JoinedBoardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart başarılı bir şekilde taşındı.
        /// </summary>
        public static string MovedCardSuccessfully {
            get {
                return ResourceManager.GetString("MovedCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolanız başarılı bir şekilde değiştirildi..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum yenileme işleminin süresi doldu. Lütfen tekrar giriş yapınız..
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum yenileme anahtarı geçerli değil. Lütfen tekrar giriş yapınız..
        /// </summary>
        public static string RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("RefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano listesi başarılı bir şekilde kaldırıldı..
        /// </summary>
        public static string RemovedBoardListSuccessfully {
            get {
                return ResourceManager.GetString("RemovedBoardListSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pano üyesi başarılı bir şekilde panodan kaldırıldı..
        /// </summary>
        public static string RemovedBoardMemberSuccessfully {
            get {
                return ResourceManager.GetString("RemovedBoardMemberSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart kontrol listesi başarılı bir şekilde kaldırıldı. .
        /// </summary>
        public static string RemovedCheckListFromCardSuccessfully {
            get {
                return ResourceManager.GetString("RemovedCheckListFromCardSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde giriş yaptınız..
        /// </summary>
        public static string SignedInSuccessfully {
            get {
                return ResourceManager.GetString("SignedInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumunuz başarılı bir şekilde yenilendi..
        /// </summary>
        public static string SignedInWithRefreshTokenSuccessfully {
            get {
                return ResourceManager.GetString("SignedInWithRefreshTokenSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı kaydınız başarılı bir şekilde yapıldı. Belirlediğiniz e-posta adresi ve şifreniz ile giriş yapabilirsiniz..
        /// </summary>
        public static string SignedUpSuccessfully {
            get {
                return ResourceManager.GetString("SignedUpSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış kullanıcı adı veya şifre!.
        /// </summary>
        public static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski şifre yanlış..
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
